CREATE DATABASE EMPLOYEE_TRACKER;

USE EMPLOYEE_TRACKER;

CREATE TABLE DEPARTMENT (
    ID INT AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE_ROLE (
    ID INT AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    SALARY DECIMAL NOT NULL,
    DEPARTMENT_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
); 

CREATE TABLE EMPLOYEE (
    ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(45) NOT NULL,
    LAST_NAME VARCHAR(45) NOT NULL,
    ROLE_ID INT,
    MANAGER_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES EMPLOYEE_ROLE(ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE_ROLE(ID)
);